services:
  - type: web
    name: text-drsyamirul
    plan: free
    numInstances: 1
    env: rust
    repo: https://github.com/dr-msr/text.git
    buildCommand: cargo build --release
    startCommand: ./target/release/microbin --editable --default-expiry never --hash-ids --hide-logo --title Dr. Syamirul --public-path https://text.drsyamirul.com
